apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  labels:
    name: nginx-configmap
data:  
  nginx.conf: |
    user nginx;
    worker_processes  1;

    # explicitly specifying the path to the mandatory error log
    error_log  /var/log/nginx/error.log warn;

    # explicitly specifying the path to the pid file
    pid        /var/run/nginx.pid;

    # sets up a new configuration context for the 'events' module
    events {
      # the product of this number and the number of worker_processes
      # indicates how many simultaneous connections per IP:port pair are
      # accepted
      
      worker_connections  1024;
    }

    http {
      client_body_temp_path /tmp/client_body_temp;
      proxy_temp_path       /tmp/proxy_temp;
      fastcgi_temp_path     /tmp/fastcgi_temp;
      uwsgi_temp_path       /tmp/uwsgi_temp;
      scgi_temp_path        /tmp/scgi_temp;

      gzip_static  on;
      gzip_proxied expired no-cache no-store private auth;

      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;
      sendfile        on;
      tcp_nopush      on;
      tcp_nodelay     on;
      keepalive_timeout  65;
      #gzip  on;

      include /etc/nginx/conf.d/*.conf;

      server_names_hash_max_size 1024

      server {
        listen 80;
        return 444;
      }

      server {
        listen 80;

        server_name www.example.com;

        location / {
          try_files $uri $uri/ @mongrel
        }

        location @mongrel {
          proxy_pass http://127.0.0.1:8080
        }
      }

    }    
    